// errors
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// users
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CLEAR_CURRENT_USER = 'CLEAR_CURRENT_USER';

// store
export const SET_CURRENT_STORE = 'SET_CURRENT_STORE';
export const CLEAR_CURRENT_STORE = 'CLEAR_CURRENT_STORE';

// cat
export const SET_CURRENT_PRODUCT_CATS = 'SET_CURRENT_PRODUCT_CATS';
export const CLEAR_CURRENT_PRODUCT_CATS = 'CLEAR_CURRENT_PRODUCT_CATS';